<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSMOv4ce\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSMOv4ce/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSMOv4ce.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSMOv4ce\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSMOv4ce\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SMOv4ce',
    'container.build_id' => 'e6ee6d39',
    'container.build_time' => 1649409763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSMOv4ce');
